services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration
    image: flask_app_integration_image:latest  # Name and tag for the Docker image
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=integration