{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temps moyen par requête",
   "type": "stat",
   "gridPos": { "h": 24, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by(endpoint) (rate(flask_http_request_duration_seconds_sum[6h]))\r\n  /\r\n  sum by(endpoint) (rate(flask_http_request_duration_seconds_count[6h]))\r\n)\r\nunless\r\n  sum by(endpoint) (rate(flask_http_request_duration_seconds_count[6h])) == 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Répartition requêtes par code dernière heure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requêtes toute les 15 minutes sur le serveur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(flask_http_request_total{status=\"200\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(flask_http_request_total{status=\"500\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}