services:
  flask_app:
    build:
      context: ..
      target: development
      dockerfile: Dockerfile
    image: ${FLASK_HOST}:latest  # Name and tag for the Docker image
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mariadb
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
    volumes:
      - ./.production/logs:/app/logs
    env_file:
      - env/dev.env
    networks:
      - flask-dev-db-network


  mariadb:
    image: mariadb:latest
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Import password from {prod}.env file
      MYSQL_DATABASE: ${MYSQL_DATABASE}       # Import database name from {prod}.env file
      MYSQL_USER: ${MYSQL_USER}                  # Import user name from {prod}.env file
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}     # Import user password from {prod}.env file
    ports:
      - "3307:3306"                     # Expose port 3306 to the host
    volumes:
      - mariadb_development:/var/lib/mysql       # Data persistence
    networks:
      - flask-dev-db-network

volumes:
  mariadb_development:

networks:
  flask-dev-db-network:
    driver: bridge

