services:
  flask_app:
    build:
      context: ..
      target: integration
      dockerfile: Dockerfile
    image: ${FLASK_HOST}:latest  # Name and tag for the Docker image
    depends_on:
      - mariadb
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    env_file:
      - env/integration.env
    networks:
      - flask-integration-db-network

  mariadb:
    image: mariadb:latest
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Import password from {prod}.env file
      MYSQL_DATABASE: ${MYSQL_DATABASE}       # Import database name from {prod}.env file
      MYSQL_USER: ${MYSQL_USER}                  # Import user name from {prod}.env file
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}     # Import user password from {prod}.env file
    ports:
      - "3308:3306"                     # Expose port 3306 to the host
    networks:
      - flask-integration-db-network

volumes:
  mariadb_development:

networks:
  flask-integration-db-network:
    driver: bridge

